CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE TYPE "public"."Category" AS ENUM('SMALL_ARMS', 'HEAVY_ARMS', 'HEAVY_AMMUNITION', 'UTILITY', 'MEDICAL', 'RESSOURCE', 'UNIFORM', 'VEHICLE', 'SHIPPABLE', 'MATERIALS', 'UNIFORMS', 'AIRCRAFT_PARTS', 'NONE');--> statement-breakpoint
CREATE TYPE "public"."Faction" AS ENUM('WARDEN', 'COLONIAL', 'NEUTRAL');--> statement-breakpoint
CREATE TYPE "public"."Class" AS ENUM('NONE', 'REVOLVER_AMMO', 'MOTORCYCLE', 'MACHINE_GUN_AMMO', 'FIELD_ARTILLERY', 'LIGHT_ARTILLERY_AMMO', 'ANTI_TANK_RIFLE_AMMO', 'HEAVY_ARTILLERY_AMMO', 'ANTI_AIR_MACHINE_GUN_AMMO', 'ASSAULT_RIFLE', 'SPIGOT_MORTAR_AMMO', 'FIELD_MORTAR', 'STORM_CANNON_AMMO', 'INFANTRY_SUPPORT_GUN_AMMO', 'HE_ROCKET_ARTILLERY_AMMO', 'LARGE_FIELD_MORTAR', 'HEAVY_FIELD_GUN', 'CANNON_AMMO', 'INCENDIARY_ROCKET_ARTILLERY_AMMO', 'EMPLACED_HEAVY_ARTILLERY', 'INFANTRY_BOAT', 'ANTI_TANK_AMMO', 'RIFLE_AMMO', 'ASSAULT_RIFLE_AMMO', 'GUNBOAT', 'LARGE_CANNON_AMMO', 'SIEGE_BOAT', 'ASSAULT_TANK', 'PISTOL_AMMO', 'DIVE_BOMBER_AMMO', 'LARGE_ANTI_TANK_AMMO', 'LARGE_FIELD_GUN', 'ANTI_AIRCRAFT_AMMO', 'SUBMACHINE_GUN_AMMO', 'SHIPPABLE_MATERIAL', 'ROCKET', 'GRENADE', 'AMPHIBIOUS_SCOUT_AIRCRAFT', 'SCOUT_AIRCRAFT', 'FIELD_AT_GUN', 'LANDING_APC', 'SUBMARINE', 'AP_RPG_AMMO', 'ARC_RPG_AMMO', 'ENTRENCHMENT', 'HEAVY_DUTY_TRUCK', 'EXPLOSIVE_CHARGE', 'MINEFIELD', 'COMBAT_CAR', 'PISTOL', 'LOGISTICS_STRUCTURE', 'FACILITY_STRUCTURE', 'AIRCRAFT_RUNWAY', 'LORE_ITEM', 'RAW_MATERIAL', 'REFINED_MATERIAL', 'FIELD_FORTIFICATION', 'ANTI_TANK_GRENADE', 'RIFLE', 'RELIC_ARMOURED_CAR', 'LARGE_MATERIAL', 'COLONIAL_PARATROOPER_UNIFORM', 'WARDEN_PILOT_UNIFORM', 'BARGE', 'STORAGE_SHIP', 'RESOURCE_SHIP', 'CRANE', 'ADVANCED_CONSTRUCTION_VEHICLE', 'MOTORBOAT', 'FREIGHTER', 'BASE_SHIP', 'LARGE_CRANE', 'FLATBED_TRUCK', 'HARVESTER', 'CONSTRUCTION_VEHICLE', 'LANDING_SHIP', 'LOCOMOTIVE', 'FIRST_AID_CAR', 'INFANTRY_CAR', 'SMALL_FLATBED_CAR', 'FLATBED_CAR', 'SMALL_TRAIN_LOCOMOTIVE', 'SMALL_CONTAINER_CAR', 'CABOOSE', 'CONTAINER_CAR', 'SMALL_BOX_CAR', 'SMALL_LIQUID_CONTAINER_CAR', 'HEAVY_FIELD_CANNON', 'FIELD_CANNON', 'MEDICAL_EQUIPMENT', 'ANTI_TANK_RPG', 'MINE_BOAT', 'FIELD_GEAR', 'LIGHT_FRIGATE', 'BICYCLE', 'ANTI_TANK_RIFLE', 'BORDER_BASE', 'BAYONET', 'SHOTGUN_AMMO', 'BATTLESHIP', 'WARDEN_SNOW_UNIFORM', 'LIGHT_MACHINE_GUN', 'MECH', 'SNIPER_RIFLE', 'LONG_RIFLE', 'WARDEN_PARATROOPER_UNIFORM', 'COASTAL_GUN', 'AIRCRAFT_PART', 'REVOLVER', 'BRIDGE', 'SHIPPABLE_CONCRETE_MIXER', 'DESTROYER', 'SHIPPABLE_CONSTRUCTION_EQUIPMENT', 'FACILITY_RAILWAY_TRACK', 'ITEM_CRATE', 'MORTAR', 'LARGE_ITEM', 'SUPER_TANK', 'MOUNTED_RPG_LAUNCHER', 'RPG_LAUNCHER', 'EMPLACED_MACHINE_GUN', 'EMPLACED_ARC_RPG', 'EMPLACED_LARGE_CANNON', 'EMPLACED_ROCKET_ARTILLERY', 'EMPLACED_ANTI_AIRCRAFT_CANNON', 'DAMAGED_AIRCRAFT_PART', 'LIGHT_FREIGHTER', 'MOUNTED_INFANTRY_SUPPORT_GUN', 'LIGHT_TANK', 'LIGHT_UTILITY_VEHICLE', 'FIELD_AT_RIFLE', 'TRANSPORT_BUS', 'FIRE_ENGINE', 'FUEL_TANKER', 'TRUCK', 'AMBULANCE', 'SEA_MINE', 'SEA_MINEFIELD', 'MELEE_WEAPON', 'EMPLACEMENT_HOUSE', 'COLONIAL_ENGINEER_UNIFORM', 'SUBMACHINE_GUN', 'UTILITY_STRUCTURE', 'MOUNTED_FLAMETHROWER_AMMO', 'MORTAR_AMMO', 'BATTLE_TANK', 'FACILITY_FOUNDATION', 'FIELD_MACHINE_GUN', 'CRUISER_TANK', 'GARRISONED_HOUSE', 'WARDEN_NAVAL_UNIFORM', 'COLONIAL_GRENADE_UNIFORM', 'WARDEN_ARMOUR_UNIFORM', 'LIGHT_INFANTRY_TANK', 'SIEGE_TANK', 'HALF_TRACK', 'FIELD_TOOL', 'MOUNTED_EXPLOSIVE_CHARGE_DETONATOR', 'WARDEN_HEAVY_AMMO_UNIFORM', 'RELIC_VEHICLES', 'COLONIAL_SNOW_UNIFORM', 'EMPLACED_LIGHT_ARTILLERY', 'EMPLACED_LARGE_ANTI_TANK_CANNON', 'WARDEN_SOLDIER_UNIFORM', 'GRENADE_LAUNCHER', 'SHOTGUN', 'MACHINE_GUN', 'KEEP', 'SCOUT_TANK', 'MOUNTED_MACHINE_GUN', 'EMPLACED_ANTI_TANK_CANNON', 'MOUNTED_EQUIPMENT', 'COLONIAL_SOLDIER_UNIFORM', 'SHIPPABLE_CONTAINER', 'COLONIAL_PILOT_UNIFORM', 'FIGHTER_AIRCRAFT', 'TORPEDO_BOMBER_AIRCRAFT', 'SUPPLIES', 'BOMBER_AMMO', 'COLONIAL_MEDIC_UNIFORM', 'AIRCRAFT_CARRIER', 'DIVE_BOMBER_AIRCRAFT', 'DEPTH_CHARGE', 'TORPEDO', 'MOUNTED_ANTI_TANK_RPG', 'MOUNTED_GRENADE_LAUNCHER', 'DESTROYER_TANK', 'ARMOURED_CAR', 'ARMOURED_ROCKET_PLATFORM', 'OBSERVATION_TOWER', 'WARDEN_OFFICER_UNIFORM', 'COLONIAL_OFFICER_UNIFORM', 'RESOURCE_HARVESTER', 'WARDEN_SCOUT_UNIFORM', 'WARDEN_TANK_UNIFORM', 'BACKPACK', 'WARDEN_MEDIC_UNIFORM', 'PREPARED_MINEFIELD', 'PROTOTYPE_KIT', 'RPG_AMMO', 'COLONIAL_RAIN_UNIFORM', 'COLONIAL_SCOUT_UNIFORM', 'HOME_BASE', 'COLONIAL_NAVAL_UNIFORM', 'RELIC_TRUCK', 'RESERVE_POWER', 'TRANSPORT_AIRCRAFT', 'GUNSHIP', 'TRAILER', 'FIELD_LAUNCHER', 'SAFE_HOUSE', 'WARDEN_ENGINEER_UNIFORM', 'DEMOLITION_ROCKET', 'RELIC_LIGHT_TANK', 'TANKETTE', 'COLONIAL_TANK_UNIFORM', 'LONG_RANGE_ARTILLERY_CAR', 'HEAVY_RIFLE', 'TRIPOD_MOUNT', 'AMPHIBIOUS_FIGHTER_AIRCRAFT', 'HEAVY_BOMBER_AIRCRAFT', 'COLONIAL_ARMOUR_UNIFORM', 'FLAMETHROWER_AMMO', 'FLAMETHROWER', 'WOUNDED_PLAYER', 'WRECKAGE', 'MOUNTED_ANTI_TANK_RIFLE');--> statement-breakpoint
CREATE TYPE "public"."SuperClass" AS ENUM('NONE', 'MAGAZINE', 'ARTILLERY_AMMO', 'ASSAULT_RIFLE', 'PROPELLED_EXPLOSIVE', 'SHELL', 'AMMUNITION', 'BOMB', 'GRENADE', 'EXPLOSIVE_CHARGE', 'PISTOL', 'RAW_RESOURCE', 'TECHNOLOGY_MATERIAL', 'ANTI_TANK_GRENADE', 'RIFLE', 'LARGE_MATERIAL', 'PARATROOPER_UNIFORM', 'PILOT_UNIFORM', 'ANTI_TANK_RPG', 'MATERIAL', 'FIELD_GEAR', 'ANTI_TANK_RIFLE', 'SHOTGUN', 'BAYONET', 'SNOW_UNIFORM', 'LIGHT_MACHINE_GUN', 'SNIPER_RIFLE', 'LONG_RIFLE', 'AIRCRAFT_PART', 'REVOLVER', 'MORTAR', 'RESOURCE', 'MOUNTED_RPG_LAUNCHER', 'RPG_LAUNCHER', 'DAMAGED_AIRCRAFT_PART', 'MOUNTED_INFANTRY_SUPPORT_GUN', 'LIQUID', 'SEA_MINE', 'MELEE_WEAPON', 'ENGINEER_UNIFORM', 'SUBMACHINE_GUN', 'NAVAL_UNIFORM', 'GAS_GRENADE', 'GRENADE_UNIFORM', 'ARMOUR_UNIFORM', 'FIELD_TOOL', 'HEAVY_AMMO_UNIFORM', 'SOLDIER_UNIFORM', 'GRENADE_LAUNCHER', 'MACHINE_GUN', 'MOUNTED_MACHINEGUN', 'UTILITY', 'SUPPLIES', 'HE_GRENADE', 'MEDIC_UNIFORM', 'DEPTH_CHARGE', 'TORPEDO', 'MOUNTED_ANTI_TANK_RPG', 'MOUNTED_GRENADE_LAUNCHER', 'OFFICER_UNIFORM', 'SCOUT_UNIFORM', 'SMOKE_GRENADE', 'TANK_UNIFORM', 'BACKPACK', 'RAIN_UNIFORM', 'HEAVY_RIFLE', 'FLAMETHROWER_AMMO', 'FLAMETHROWER', 'MOUNTED_ANTI_TANK_RIFLE');--> statement-breakpoint
CREATE TYPE "public"."LocationType" AS ENUM('STORAGE_DEPOT', 'SEAPORT');--> statement-breakpoint
CREATE TYPE "public"."MapMarkerType" AS ENUM('MAJOR', 'MINOR');--> statement-breakpoint
CREATE TABLE "Item" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"frName" text,
	"shortName" text,
	"category" "Category" NOT NULL,
	"superClass" "SuperClass" NOT NULL,
	"class" "Class" NOT NULL,
	"faction" "Faction" DEFAULT 'NEUTRAL' NOT NULL,
	"nbByCrate" integer DEFAULT 100 NOT NULL,
	"maxQuantity" integer DEFAULT 100 NOT NULL,
	"icon" text,
	"attributes" jsonb,
	"createdAt" timestamp (3) DEFAULT now() NOT NULL,
	"updatedAt" timestamp (3) DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Location" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" "LocationType" DEFAULT 'SEAPORT' NOT NULL,
	"faction" "Faction" DEFAULT 'NEUTRAL' NOT NULL,
	"iconType" integer DEFAULT 0 NOT NULL,
	"flags" integer DEFAULT 0 NOT NULL,
	"viewDirection" integer DEFAULT 0 NOT NULL,
	"longitude" double precision NOT NULL,
	"latitude" double precision NOT NULL,
	"townId" uuid NOT NULL,
	"regionId" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "Region" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"gameRegionId" integer
);
--> statement-breakpoint
CREATE TABLE "Town" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"longitude" double precision NOT NULL,
	"latitude" double precision NOT NULL,
	"mapMarkerType" "MapMarkerType" NOT NULL,
	"regionId" uuid NOT NULL
);
--> statement-breakpoint
ALTER TABLE "Location" ADD CONSTRAINT "Location_townId_fkey" FOREIGN KEY ("townId") REFERENCES "public"."Town"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Location" ADD CONSTRAINT "Location_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "public"."Region"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Town" ADD CONSTRAINT "Town_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "public"."Region"("id") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "Item_name_idx" ON "Item" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "Item_frName_idx" ON "Item" USING gin ("frName" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "Item_name_key" ON "Item" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "Item_shortName_idx" ON "Item" USING gin ("shortName" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "Location_longitude_latitude_key" ON "Location" USING btree ("longitude" float8_ops,"latitude" float8_ops);--> statement-breakpoint
CREATE INDEX "Region_name_idx" ON "Region" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "Region_name_key" ON "Region" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "Town_name_idx" ON "Town" USING gin ("name" gin_trgm_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "Town_name_regionId_key" ON "Town" USING btree ("name" text_ops,"regionId" uuid_ops);
--> statement-breakpoint
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER item_updated_at
  BEFORE UPDATE ON "Item"
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();--> statement-breakpoint