import type { LocationType } from '@57eme-regiment/krang-api-contract';

export const imageBaseUrl = 'https://foxhole.wiki.gg/images/';

export const IconTypeMap: Record<number, string> = {
  5: 'MapIconStaticBase1.png',
  6: 'MapIconStaticBase2.png',
  7: 'MapIconStaticBase3.png',

  8: 'MapIconBunkerBaseTier1.png',
  9: 'MapIconBunkerBaseTier2.png',
  10: 'MapIconBunkerBaseTier3.png',

  11: 'MapIconHospital.png',
  12: 'MapIconVehicle.png',
  16: 'MapIconManufacturing.png',
  17: 'MapIconManufacturing.png',
  18: 'Shipyard.png',
  19: 'BlueprintIcon.png',

  20: 'SalvageMapIcon.png',
  21: 'MapIconComponents.png',
  22: 'MapIconFuel.png',
  23: 'MapIconSulfur.png',
  28: 'MapIconObservationTower.png',
  29: 'FortStructureIcon.png',
  32: 'MapIconSulfurMine.png',
  33: 'MapIconStorageFacility.png',
  34: 'MapIconFactory.png',
  37: 'MapIconRocketSiteWithRocket.png',
  38: 'MapIconScrapMine.png',
  39: 'MapIconConstructionYard.png',
  40: 'MapIconComponentMine.png',
  41: 'OilWellMineIcon.png',

  45: 'MapIconRelicBase.png',
  46: 'MapIconRelicBase.png',
  47: 'MapIconRelicBase.png',

  51: 'MapIconMassProductionFactory.png',
  52: 'MapIconSeaport.png',
  53: 'MapIconCoastalGun.png',

  56: 'MapIconTownBaseTier1.png',
  57: 'MapIconTownBaseTier2.png',
  58: 'MapIconTownBaseTier3.png',

  59: 'MapIconStormcannon.png',
  60: 'MapIconIntelcenter.png',

  61: 'MapIconCoal.png',
  62: 'MapIconFuel.png',

  72: 'MapIconRocketSiteWithRocket.png',

  83: 'MapIconWeatherStation.png',
  84: 'MapIconMortarHouse.png',

  88: 'MapIconAircraftDepot.png',
  89: 'FacilityFactoryAircraftIcon.png',
  90: 'MapIconFortLargeRadar.png',
  91: 'MapIconAircraftRunwayT1.png',
  92: 'MapIconAircraftRunwayT2.png',
};

export const LocationTypeByIconMap: Record<number, LocationType> = {
  5: 'SPAWN_STORAGE',
  6: 'SPAWN_STORAGE',
  7: 'SPAWN_STORAGE',
  8: 'FORWARD_BASE',
  9: 'FORWARD_BASE',
  10: 'FORWARD_BASE',
  11: 'MEDICAL_BASE',
  12: 'PRODUCTION',
  13: 'NEUTRAL_STRUCTURE',
  14: 'NEUTRAL_STRUCTURE',
  15: 'NEUTRAL_STRUCTURE',
  16: 'PRODUCTION',
  17: 'PRODUCTION',
  18: 'PRODUCTION',
  19: 'WORLD_STRUCTURE',
  20: 'RESOURCE_FIELD',
  21: 'RESOURCE_FIELD',
  22: 'RESOURCE_FIELD',
  23: 'RESOURCE_FIELD',
  28: 'AUTOMATED_DEFENSE',
  29: 'SPAWN_STORAGE',
  32: 'RESOURCE_HARVESTER',
  33: 'STORAGE',
  34: 'PRODUCTION',
  36: 'PRODUCTION',
  37: 'PRODUCTION',
  38: 'RESOURCE_HARVESTER',
  39: 'PRODUCTION',
  40: 'RESOURCE_HARVESTER',
  41: 'RESOURCE_HARVESTER',
  45: 'HOME_BASE',
  46: 'HOME_BASE',
  47: 'HOME_BASE',
  51: 'PRODUCTION',
  52: 'STORAGE',
  53: 'AUTOMATED_DEFENSE',
  54: 'PRODUCTION',
  56: 'HOME_BASE',
  57: 'HOME_BASE',
  58: 'HOME_BASE',
  59: 'PLAYER_MANNED_DEFENSE',
  60: 'PLAYER_MANNED_DEFENSE',
  61: 'RESOURCE_FIELD',
  62: 'RESOURCE_FIELD',
  70: 'UTILITY',
  71: 'UTILITY',
  72: 'UTILITY',
  83: 'PLAYER_MANNED_DEFENSE',
  84: 'PLAYER_MANNED_DEFENSE',
  88: 'STORAGE',
  89: 'PRODUCTION',
  90: 'PLAYER_MANNED_DEFENSE',
  91: 'UTILITY',
  92: 'UTILITY',
};
